### ISSUE TITLE
Variants from nested modules are not recognized

### ISSUE THREAD

**Issue by szymanskip** [bitrise-io/go-android#28]
I have the following project structure:

```
moduleA
|-build.gradle
directory
|-moduleB
|---build.gradle
|-moduleC
|---build.gradle
```

All the modules are included in `settings.gradle`.
Modules B and C are being "grouped" in a directory and they can be referenced from Gradle with `:directory:moduleB` and `:directory:moduleC`.
By the looks of it, those modules are being ignored when querying for tasks and building a list of variants.
Related code: https://github.com/bitrise-io/go-android/blob/8082fe069ed29f394c2fd0724dd6bdc64e5cf6b4/gradle/task.go#L46-L50

I would love to help and fix that but is there a way to run the Go code locally on my project?

**Comment by fehersanyi-bitrise** [comment]
Hy @szymanskip 
you could use the bitrise CLI locally to debug it: https://app.bitrise.io/cli

**Comment by szymanskip** [comment]
Thanks! I will give it a go when I have some time. In the meantime, I will reconfigure my workflow to use Gradle tasks directly.
