### ISSUE TITLE
Gradle nested modules seem to be not supported

### ISSUE THREAD

**Issue by ikesyo** [bitrise-io/go-android#30]
http://www.developerphil.com/nested-modules-in-gradle/

e.g.:
- `:feature:foo:testDevelopDebugUnitTest`
- `:feature:bar:testDevelopDebugUnitTest`

It seems that nested modules are not supported in `parseVariants`: https://github.com/bitrise-io/go-android/blob/34d6f20488bf0e2256c034c03a2a589a4a608e3f/gradle/task.go#L26-L77

**Comment by ofalvai** [comment]
I'm closing this old issue because `go-android` now supports parsing nested modules.
